#!/usr/bin/env bash
# =============================================================================
# create-app.sh
# Usage:    pnpm create:app <app-name>
# Example:  pnpm create:app shadcn-ui
#
# Automatically build a Vite + React + TypeScript + Vitest environment in apps/<app-name>/
# =============================================================================
set -euo pipefail

# ── argument check ──────────────────────────────────────────────────────────
APP_NAME="${1:-}"
if [[ -z "$APP_NAME" ]]; then
  echo "Usage:    pnpm create:app <app-name>"
  echo "Example:  pnpm create:app shadcn-ui"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/apps/$APP_NAME"

if [[ -d "$APP_DIR" ]]; then
  echo "Error: apps/$APP_NAME already exists"
  exit 1
fi

echo ""
echo "🚀 Creating apps/$APP_NAME ..."
echo ""

# ── Step 1: Generate Vite project (dependencies will be installed later) ───────
echo "📁 [1/5] Generating Vite project..."
cd "$REPO_ROOT"

# Optionally: pass --skip-install to prevent automatic installation when running pnpm create
pnpm create vite "apps/$APP_NAME" --template react-ts

# ── Step 2: Replace configuration files ───────────────────────────────────────
echo "⚙️  [2/5] Creating configuration files..."
cd "$APP_DIR"

# Remove files generated by Vite and replace them with custom ones
rm -f tsconfig.app.json vite.config.ts eslint.config.js eslint.config.ts

# tsconfig.app.json (inherits common settings from the root, for app code)
cat > tsconfig.app.json << 'TSCONFIG_APP'
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "types": ["vite/client", "vitest/globals", "@testing-library/jest-dom"],
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "moduleDetection": "force",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "erasableSyntaxOnly": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
TSCONFIG_APP

# vite.config.ts
cat > vite.config.ts << 'VITE_CONFIG'
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["@yap-react-ui-sandbox/test-config/setup"],
    globals: true,
  },
});
VITE_CONFIG

# ── Step 3: Install devDependencies ─────────────────────────────────────────
echo "📦 [3/5] Installing devDependencies..."

# First, install the basic devDependencies generated by Vite (if not already installed)
pnpm install

# Add test-related packages
pnpm add -D \
  vitest \
  "@vitest/ui" \
  jsdom \
  "@testing-library/react" \
  "@testing-library/user-event" \
  "@yap-react-ui-sandbox/test-config@workspace:*" \
  "@yap-react-ui-sandbox/playground@workspace:*"

# Reinstall at the workspace root (to establish workspace:* links)
cd "$REPO_ROOT"
pnpm install
cd "$APP_DIR"

# ── Step 4: Add scripts to package.json ─────────────────────────────────────
echo "📝 [4/5] Adding scripts to package.json..."
node --input-type=module << 'SCRIPT'
import { readFileSync, writeFileSync } from "fs";

const pkgPath = "package.json";
const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));

pkg.scripts = {
  "dev":             "vite",
  "build":           "tsc -b && vite build",
  "preview":         "vite preview",
  "test":            "vitest run",
  "test:watch":      "vitest",
  "test:ui":         "vitest --ui",
  "test:coverage":   "vitest run --coverage",
  "storybook":       "storybook dev -p 6006",
  "build-storybook": "storybook build",
};

pkg.volta = {
  extends: "../../package.json"
};

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
console.log("Updated scripts");
SCRIPT

# ── Step 5: Create sample test files ─────────────────────────────────────────
echo "🧪 [5/5] Creating sample test files..."
mkdir -p src/__tests__

cat > src/__tests__/App.test.tsx << 'SAMPLE_TEST'
import { render } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import App from "../App";

describe("App", () => {
  it("renders without crashing", () => {
    render(<App />);
    expect(document.body).toBeInTheDocument();
  });
});
SAMPLE_TEST

# ── Completion message ──────────────────────────────────────────────────────
echo ""
echo "✅ apps/$APP_NAME has been created!"
echo ""
echo "Next steps:"
echo "  cd apps/$APP_NAME"
echo "  pnpm dev          # Start development server (http://localhost:5173)"
echo "  pnpm test:watch   # Run tests in watch mode"
echo ""
echo "If you want to add Storybook:"
echo "  cd apps/$APP_NAME"
echo "  pnpm dlx storybook@latest init"
echo ""
